//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMagazine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public Classes()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Класс { get; set; }
        public string Учебный_год { get; set; }
        public Nullable<int> Id_Дисциплины { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual ICollection<Students> Students { get; set; }
    }
}
