//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMagazine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public Discipline()
        {
            this.Classes = new HashSet<Classes>();
            this.Grades = new HashSet<Grades>();
            this.Teachers = new HashSet<Teachers>();
        }
    
        public int Id { get; set; }
        public string Дисциплина { get; set; }
    
        public virtual ICollection<Classes> Classes { get; set; }
        public virtual ICollection<Grades> Grades { get; set; }
        public virtual ICollection<Teachers> Teachers { get; set; }
    }
}
