//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMagazine
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTeacher
    {
        public int Id { get; set; }
        public Nullable<int> Id_Group { get; set; }
        public Nullable<int> Id_Teacher { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
