//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMagazine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public Students()
        {
            this.Grades = new HashSet<Grades>();
        }
    
        public int Id { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> Id_Класса { get; set; }
        public Nullable<int> Id_User { get; set; }
    
        public virtual ICollection<Grades> Grades { get; set; }
        public virtual Users Users { get; set; }
    }
}
