//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicMagazine
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public int Id { get; set; }
        public string Имя_ { get; set; }
        public string Фамилия { get; set; }
        public Nullable<int> Id_Дисциплины { get; set; }
        public Nullable<int> id_User { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Users Users { get; set; }
    }
}
